config/routes.rb
Rails.application.routes.draw do
  
  root "static_pages#home"

  match "help", to: "static_pages#help", via: :get

  get    'about'   => 'static_pages#about'

  get    'contact' => 'static_pages#contact'

  get    'signup'  => 'users#new'
         
  get    'signin'  => 'sessions#new'

  delete 'signout' => 'sessions#destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :account_activation, only: [:edit]
  resources :password_reset, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]

end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  
  before_action :get_user, only: [:edit, :update]
  before_action :verify_user, only: [:edit, :update]
  before_action :expiration_check, only: [:edit, :update]

  def new
  end

  def create
  	@user = User.find_by email: params[:password_reset][:email]

  	if @user 
  		flash[:info] = 'Check your email for password reset details'
  		@user.create_password_reset
  		@user.update_columns(reset_digest: @user.reset_digest, reset_sent_at: Time.now.to_datetime)
  		UserMailer.password_reset(@user).deliver_now
  		redirect_to root_url
  	else
  		flash.now[:danger] = 'There is no such email it the database'
  		render :new
  	end
  end

  def edit
  end

  def update
  	if password_blank?
  		flash.now[:info] = "Password can't be blank"
  		render :edit
  	elsif @user.update_attributes(user_params)
  		flash[:success] = 'Password has been updated'
  		sign_in @user
  		redirect_to @user
  	else
  		render :edit
  	end
  end

  private
  	def verify_user
  		unless @user && @user.activated? && @user.authenticated?(:reset, params[:id])
  			redirect_to root_url
  		end
  	end

  	def get_user
  		@user = User.find_by email: params[:email]
  	end

  	def user_params
  		params.require(:user).permit(:password, :password_confirmation)
  	end

  	def password_blank?
  		params[:user][:password].blank?
  	end

  	def expiration_check
  		if @user.password_reset_expired?
  			flash[:danger] = 'Link has expired'
  			redirect_to new_password_reset_url
  		end
  	end
end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/views/password_reset/edit.html.erb
<% provide :title, "Password Reset" %>
<h1>Password Reset</h1>
<%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>

	<%= render "shared/error_messages" %>

	<%= hidden_field_tag :email, @user.email %>

	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label :password_confirmation, 'Confirm' %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>

	<%= f.submit 'Reset Password', class: 'btn btn-primary' %>
<%end%>

app/views/password_reset/new.html.erb
<% provide :title, "Password Reset" %>
<h1>Password Reset</h1>
<%= form_for(:password_reset, url: password_reset_index_path) do |f| %>
	<%= f.label :email %>
	<%= f.email_field :email, class: 'form-control' %>

	<%= f.submit 'Send', class: 'btn btn-primary' %>
<%end%>