config/routes.rb
Rails.application.routes.draw do
  
  root "static_pages#home"

  match "help", to: "static_pages#help", via: :get

  get    'about'   => 'static_pages#about'

  get    'contact' => 'static_pages#contact'

  get    'signup'  => 'users#new'
         
  get    'signin'  => 'sessions#new'

  delete 'signout' => 'sessions#destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :account_activation, only: [:edit]
  resources :password_reset, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
	</small>
	<nav>
		<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
				<li><a href="http://news.railstutorial.org/">News</a></li>
			</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%=link_to 'sample app', root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", help_path %></li>
				<% if signed_in? %>
					<li><%= link_to 'Users', users_path %></li>
					<li class='dropdown'>
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Account <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><%= link_to 'Profile', current_user %></li>
							<li><%= link_to 'Settings', edit_user_path(current_user) %></li>
							<li class='divider'></li>
							<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
						</ul>
					</li>
				<%else%>
					<li><%= link_to "Sign in", signin_path %></li>
				<%end%>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield :title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<%= content_tag :div, value, class: "alert alert-#{key}" %>
		<%end%>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<br>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>